[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "style", "index.html"]

[serve]
port = 8080
open = true

# File type handling
[serve.static_file_extensions]
".css" = "text/css"

# Correctly serve style directory files
[[serve.proxied_static_files]]
mount_point = "/style"
assets = ["style"] 