# [[hooks]]
# stage = "pre_build"
# command = "npx"
# command_arguments = [
#   "tailwindcss", 
#   "build", 
#   "-i", "style/main.css", 
#   "-o", "style/output.css",
#   "--watch",
# ]

[build]
target = "index.html"
release = false
dist = "dist"
public_url = "/"

[watch]
watch = ["src", "style", "index.html"]

[serve]
port = 8080
open = true 
